### ISSUE TITLE
Bug - DFN3 mistakenly silences some voices as compared to DFN2 and DFN1

### ISSUE THREAD

**Issue by ZacharyYarostTechsmith** [Rikorose/DeepFilterNet#464]
Hello! Firstly I'd like to thank you for your work building this library and model. It's an absolutely fantastic project.

While testing DFN I've found a scenario in which version 3 silences human speech, even in a mostly noise free environment. [Here is a video](https://youtu.be/ddPqQmMLiOk?si=lulyO9Nd92cdBXM_) comparing the outputs of version 1, 2, and 3 with one such example.

I'd be grateful to get your feedback on this behavior. I question if it's simply filtering out audio below a certain volume threshold.

I've attached the associated example clips below.

[LowVolumeSpeakerTesting_Mono_48kHz_16Bit.zip](https://github.com/Rikorose/DeepFilterNet/files/13394214/LowVolumeSpeakerTesting_Mono_48kHz_16Bit.zip)

**Comment by ZacharyYarostTechsmith** [comment]
I've yet to find the shift between DFN2 and DFN3 that leads to this behavior. I'm commenting to remove the stale label.

**Comment by doctorcolossus** [comment]
Hey dude, it sucks that nobody has responded to this. Your video demonstrating the issue is great, but it would help to also share your exact code to reproduce it. How are you loading and running the models and which parameters are you using, especially for `atten_lim` and `min_db_thresh`?

**Comment by ZacharyYarostTechsmith** [comment]
@doctorcolossus Hey! It's been a very long time since I've looked more deeply into this project. I remember setting both of those values unreasonably low and having the same issue still occur.

> How are you loading and running the models

I had just been using the provided sample project! I'd have to pull out an old machine to find the exact command line call with params though. I believe it was just the readme recommendation with my own files subbed in.

**Comment by doctorcolossus** [comment]
Cool, I actually hadn't even tried the demo program before, as I initially just tried [the huggingface demo](https://huggingface.co/spaces/hshr/DeepFilterNet2), felt satisfied with it, and from there went directly to using the pre-built ladspa plugin, the PyTorch library, and the Python/Rust bindings. All of these work for me, although I did have to tweak the parameters to get good results. I've just tried the demo program, and I don't seem to experience the same issue as you did with it either. I invoked it like this:

```
DeepFilterNet/target/release $ ./df-demo --model ../../models/DeepFilterNet2_onnx.tar.gz 
DeepFilterNet/target/release $ ./df-demo --model ../../models/DeepFilterNet3_onnx.tar.gz 
DeepFilterNet/target/release $ ./df-demo --model ../../models/DeepFilterNet.zip 
```

However, the demo program doesn't seem consistent with your demo, since it doesn't appear to allow processing a recorded file, which it seems like you did in the demo, and it instead displays dual live spectrograms of the unprocessed and processed mic input respectively. It also doesn't appear to allow setting `min_db_thresh`, but instead has sliders in the GUI only for "Noise Attenuation [dB]" and "Post Filter Beta".

Maybe you used the command-line program. That also worked correctly for me with DeepFilterNet3, but I actually couldn't get it to work with the provided model files for DeepFilterNet2 or OG DeepFilterNet:

```
$ ./deep-filter --model ../../models/DeepFilterNet3_onnx.tar.gz original.wav

$ ./deep-filter --model ../../models/DeepFilterNet2_onnx.tar.gz original.wav

thread 'main' (399368) panicked at .cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tract-core-0.21.4/src/ops/change_axes.rs:849:17:
not yet implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ ./deep-filter --model ../../models/DeepFilterNet.zip original.wav
[2025-11-26T11:22:57Z ERROR deep_filter] Error opening model ../../models/DeepFilterNet.zip: Could not open model tar entry.
```

Anyway, I was just chiming in to see if I could help out, but I'm not an expert on this library either, and it sounds like maybe you aren't concerned with trying to get it working any longer. But if you are and do still experience this issue, I think it could be helpful to check and/or post spectrograms (for example using `spek` or `sox`) and/or waveform visualizations of the output of DFN3 to see whether it's actually totally silent/blank or just subjectively seems that way, as well as to post the exact commands you ran, since those might help others to replicate the issue.
