### ISSUE TITLE
Getting a Warn message Underrun detected (RTF: 1.15). Processing too slow

### ISSUE THREAD

**Issue by hakdag** [Rikorose/DeepFilterNet#482]
I used to following instructions:
https://github.com/Rikorose/DeepFilterNet/blob/main/ladspa/filter-chain-configs/deepfilter-mono-source.conf

My system is Ubuntu 23.10
I want to use DeepFilterNet to reduce environment noice during meetings. I did some testing it is actually working.
But in the terminal I am getting this error:

2023-12-25T15:07:53.923Z | WARN |  deep_filter_ladspa | DF 2c057a7acc48 | Underrun detected (RTF: 1.15). Processing too slow!

In addition to that, as soon as I open Zoom I am getting this error consequently:
2023-12-25T15:05:41.386Z | WARN |  df::tract | Possible clipping detected (1.051).

Also, there is a delay when I talk.

**Comment by Rikorose** [comment]
This warning means that your CPU is too slow. Ideally, we want a real time factor (RTF) << 1. DeepFilterNet tries to work around this problem by adding an additional delay so that single underruns are compensated by the extra buffer. However, this does not work if you get too many underruns. You can try to increase verbosity to get more information about the delay.

The clipping warning indicates that you microphone volume setting is too loud. Try to slightly decrease it.

**Comment by hakdag** [comment]
Currently I am using DeepFilterNet on an Ubuntu machine not a VM. And this machine has i9 13th gen. Dont think it is slow.
I want to try out " we want a real time factor (RTF) << 1" how can I do that?
Thanks!

**Comment by 103sbavert** [comment]
getting the same problem with pipewire here
